import React, {FunctionComponent, PropsWithChildren} from 'react'
import {Metadata} from 'next'
import {TheHeader} from '@/components/theHeader/TheHeader'
import {TheFooter} from '@/components/theFooter/TheFooter'

import styles from '../../app/styles/Layout.module.scss'
import {HeaderTwo} from "@/components/HeaderTwo/HeaderTwo";

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app'
}

interface Props extends PropsWithChildren {
    isFooterHidden?: boolean;
    Header?: string;
}

const Layout: FunctionComponent<Props> = ({children, isFooterHidden = false, Header}) => {
    return (
        <div className={styles.wrapperContent}>

            {Header === 'home' ? (
                    <div className={styles.header}>
                        <TheHeader/>
                    </div>
                ) :
                <div className={styles.header}>
                    <HeaderTwo/>
                </div>
            }

            <main className={styles.conteiner}>{children}</main>

            {!isFooterHidden && (
                <div className={styles.footer}>
                    <TheFooter/>
                </div>
            )}
        </div>
    )
}


export default Layout